Feature: add Gaussian sampler
janet-lang/spork pull request #169
Opened 2024-01-11 06:20 UTC by hyiltiz

- Add a Gaussian sampler
- Add a convenience function `sample-n` that converts a sampler to a generator

2024-01-11 07:40 UTC, pepe requested changes
Consider adding a test for the new functionality.

2024-01-11 07:53 UTC, sogaiu commented
[This line](https://github.com/janet-lang/spork/blob/0b5c8fc0dd21318d0254b1356bc0abad088e74dd/spork/randgen.janet#L45) doesn't look right.

2024-01-11 07:55 UTC, sogaiu commented
Not sure what's better, but may be `forever` could be used like this:

```janet
(defn rand-gaussian
  "Get a random sample from the standard Gaussian distribution.
  Optionall specify the mean m and the standard deviation sd. E.g.:
  (rand-gaussian) # => 0.1324...
  (rand-gaussian 5 0.1) # => 5.3397...
  "
  [&opt m sd]
  (default [m sd] [0 1])
  (defn scale [x] (+ m (* sd x)))

  (forever
    (def p (rand-uniform))
    (def q (rand-uniform))

    # We use the Box-Muller transform
    (let [rho (math/sqrt (* -2 (math/log q)))
          theta (* 2 math/pi p)
          _box    (* rho (math/cos theta))
          _muller (* rho (math/sin theta))
          box    (scale _box)
          muller (scale _muller)]

      (yield box)
      (yield muller))))
```

2024-01-11 07:55 UTC, sogaiu commented
Regarding the testing comment above, the examples in the docstrings could be broken out as tests.

2024-01-11 17:07 UTC, hyiltiz commented on spork/randgen.janet
> +  (math/rng-uniform ))
Formatted; thanks for the recommendation!

2024-01-11 17:09 UTC, hyiltiz commented
- removed leftover code
- reformatted with `spork/fmt`
- added a test following #165

2024-01-12 15:39 UTC, hyiltiz commented
Currently, we have the following problems: 
- PA: evaluating it with same rng multiple times for testing and reproduce; 
- PB: re-use muller values for efficiency; 
- PC: can be called alone and with sample-n

@sogaiu proposed [an alternative implementation](https://gist.github.com/sogaiu/ec2d4387d710d20d2169ef289dcaa52a) using a "closure"-like mechanism.

My original implementation via fibers (using `yield`) couldn't satisfy PC. I think this implementation satisfies them all.

2024-01-18 14:52 UTC, sogaiu commented
@hyiltiz and I are comparing the implementation above with his simpler one:

```janet
(defn rand-gaussian [&opt m sd]
  (default m 0)
  (default sd 1)
  (defn scale [x] (+ m (* sd x)))

  (def p (math/rng-uniform (get-rng)))
  (def q (math/rng-uniform (get-rng)))

  # We use the Box-Muller transform
  (let [rho (math/sqrt (* -2 (math/log q)))
        theta (* 2 math/pi p)
        _box (* rho (math/cos theta))
        box (scale _box)]
    box))
```

This latest one is faster and simpler:

```
(set-seed 1)

(timeit-loop [:timeout 1] "simpler" (rand-gaussian-simpler))

(set-seed 1)

(timeit-loop [:timeout 1] "complex" (rand-gaussian-complex))

# simpler 1.000s, 0.485µs/body
# complex 1.000s, 0.8271µs/body
```

2024-01-19 03:30 UTC, closed without merging